"""made function_used attribute nullable

Revision ID: 044a2227a503
Revises: fad3356a0bd2
Create Date: 2023-07-18 18:06:23.575176

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '044a2227a503'
down_revision = 'fad3356a0bd2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_log', schema=None) as batch_op:
        batch_op.alter_column('function_used',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_log', schema=None) as batch_op:
        batch_op.alter_column('function_used',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)

    # ### end Alembic commands ###
