"""make asn nullable (for admin added users with no ASN)

Revision ID: 5e56ba134ec4
Revises: b0faa4d55efd
Create Date: 2023-07-17 22:06:13.684886

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e56ba134ec4'
down_revision = 'b0faa4d55efd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('asn',
               existing_type=sa.VARCHAR(length=80),
               nullable=True,
               unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('asn',
               existing_type=sa.VARCHAR(length=80),
               nullable=False,
               unique=True)

    # ### end Alembic commands ###
